### ISSUE TITLE
Fullstack-projektin koodikatselmointi

### ISSUE THREAD

**Issue by ShootingStar91** [minnaRon/workhelper#1]
# Fullstack-projektin koodikatselmointi

Tämä on katselmointi fullstack-projektistasi. Voit halutessasi hyödyntää tässä annettuja vinkkejä ja parannusehdotuksia, mutta sinun ei tarvitse tehdä muutoksia projektiisi saadaksesi siitä suorituksen.

### Mitä tein

+ Rekisteröidyin ja kirjauduin sovellukseen
+ Lisäsin työtehtävän
+ Vaihdoin työaikaa
+ Koitin muuttaa työaikaa itse päivämäärävalitsimista
+ Lisäsin tehtäviä
+ Aloitin työajanseurannan
+ Kirjauduin ulos

### Palaute käyttäjäkokemuksesta

+ Sovellus kaatui kun yritin muuttaa päivämäärää työaikaa valittaessa
+ Päivämäärävalitsimissa oli kuukausi ensin, suomalaisittain parempi järjestys on DD/MM/YYYY
+ Uuden työn lisääminen toimi erikoisesti, mitään lisäyspainiketta ei ollut joten painoin Enteriä, jolloin sovellus menikin working-tilaan (siis tilaan jossa työ on alkanut ja sovellus näyttää taukoajat)
+ Working-tilasta ei myöskään päässyt pois muuten kuin kirjautumalla ulos ja takaisin sisään. Vaikka asetuksia pääsi muuttamaan sivuvalikosta, olisin toivonut tapaa päästä takaisin näkymään jossa sivusto on koko sivun levyinen
+ Käyttöliittymä on muuten selkeä ja tyylikäs
+ Rekisteröityminen ja kirjautuminen on helppoa.

### Palaute koodista 

+ READMEssa ollut linkki työaikakirjanpitoon ei toiminut, mutta löysin sen dokumentaatio-kansiosta.

Frontend:

+ Koodi on pääosin ymmärrettävää ja hyvää Reactia
+ Hookkeja ja reduxia käytetty fiksusti toimintojen ja tilan hallintaan
+ Välttäisin ns. nested ternaryä, esim. components/appBar/index.jsx return-lause. Koodia ensikertaa lukiessa ei ole ihan helppo pysyä kärryillä siitä, milloin mitäkin renderöidään. Tätä voi välttää vaikkapa jakamalla renderöintiä useampaan komponenttiin

Backend:

+ Koodi on hyvin jaoteltua ja selkeää myös backendissä
+ Middlewareja on käytetty hyvin

Sekä frontendille että backendille löytyy testejä, hyvä! Myös dockeria on käytetty.

Sovelluksesta löytyy siisti ulkoasu ja se toteuttaa hyvin halutun toiminnallisuuden. Vaikka muutamia parannuskohteita löytyi, käyttöliittymä on pääosin käytännöllinen ja tyylikäs. Koodi on hyvää ja hyödyntää hyviä kirjastoja ja käytänteitä. Myös sovelluksen käyttöohje on kattava. Hyvää työtä!

**Comment by minnaRon** [comment]
Kiitoksia hyvistä huomioista! Laitan ne tuonne tehtävälistaan ja otan vähitellen työn alle samalla kun rakentelen uusia toimintoja. Olin tänään sovelluksen muistiinpano -toiminnallisuutta rakentelemassa ja poistin välillä sanaston tietokannasta, kun lisäilin uusia kohtia, joten saattoi aiheuttaa hieman häiriöitä toimintaan sekin. Hyvä, että toimi suht hyvin silti ja sait ainakin jonkinlaisen käyttökokemuksen toteutettua. Kiitoksia sinulle!
